### ISSUE TITLE
Notifications from Magnetometer Bearing characteristic do not seem to work

### ISSUE THREAD

**Issue by bluetooth-mdw** [lancaster-university/microbit-dal#114]
Tested 1.4.17 with nRF Master Control Panel. Notifications are never received.

**Comment by jamesadevine** [comment]
@martinwork could you retest against master?

**Comment by martinwork** [comment]
Related to #100 and #78?

I think the problem was that the build I was testing (1.4.x) did not trigger a call to calibrate the compass. With firmware based on the current 2.0.0 master, calibration is triggered when the MicroBitMagnetometerService object is created during the first reset after flashing. After that the bearings arrive as expected. However the bearings seem quite random. I suspect I am not playing the game right!

**Comment by jamesadevine** [comment]
@martinwork  - or you're in a noisy environment :smile:

Shall we close this then?

**Comment by martinwork** [comment]
It was opened by the other Martin

**Comment by jamesadevine** [comment]
Yes - we should wait for final confirmation from @bluetooth-mdw 

Thanks for testing @martinwork !
