### ISSUE TITLE
reuse variables in recalculatePitchRoll

### ISSUE THREAD

**Issue by pelikhan** [lancaster-university/microbit-dal#116]
Seems that x,y could be reused in this expression.
https://github.com/lancaster-university/microbit-dal/blob/master/source/drivers/MicroBitAccelerometer.cpp#L644

**Comment by finneyj** [comment]
Thanks @pelikhan.

Suspect this is a due to a recent patch, as the ARMCC compiler on mbed.org doesn't support atan2() for floats - only doubles. (not sure why it does transparently upcast this though!).

As these are all just local vars though, can't see a reason not to use doubles throughout the function and get this reuse.

**Comment by finneyj** [comment]
fixed in master.
