### ISSUE TITLE
MicroBitSerial misbehaving when used in an event handler

### ISSUE THREAD

**Issue by bluetooth-mdw** [lancaster-university/microbit-dal#124]
When used in an event handler, uBit.serial.send only works once (i.e. output only appears in a connected serial console once) and subsequent calls seem to have no effect.

**Comment by jamesadevine** [comment]
Hi @bluetooth-mdw, thanks for raising this on GitHub!

This was a bug for fibers already in a fork on block context. `fiber_wait_for_event` would then create a new fiber, but not initialise any state for that fiber as it presumed `schedule()` would be called immediately after. The scheduler would then swap in an invalid fiber, and the device would go boom boom! :smile:

This was fixed by:

7cf98c2290f5fb1d0e86726e9141f6f1ff4e0994
